name: Publish musl docker image
on:
  push:
    branches:
      - main
    paths:
      - /musl.Dockerfile
  schedule:
    - cron: "26 8 * * 1"

env:
  DOCKERPLATFORM: "linux/amd64"

jobs:
  android_musl:
    runs-on: ubuntu-latest
    name: Publish Server image
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker image
        id: pre_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: musl.Dockerfile
          push: true
          tags: ghcr.io/the-bds-maneger/android_musl:latest
          platforms: ${{ env.DOCKERPLATFORM }}
