name: PHP Bin build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 6"

jobs:
  # MacOS Build
  macos:
    runs-on: macos-latest
    name: MacOS
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: pmmp/php-build-scripts
          submodules: true

      - name: Install dependecies
        run: brew install libtool autoconf automake pkg-config bison re2c

      - name: "Building php to MacoS
        env: 
          LDFLAGS: "-L /usr/local/opt/bison/lib"
        continue-on-error: true
        run: |
          export PATH="/usr/local/opt/bison/bin:${PATH}"
          ./compile.sh -t mac-x86-64 -f -g -j$(nproc)

      - name: Show Log
        run: cat *.log

      - name: Create tarball
        run: zip macos_x64.zip bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos_x64
          path: |
            *.zip
            *.log

  # MacOS Build
  macosarm64:
    runs-on: macos-latest
    name: MacOS arm64
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: pmmp/php-build-scripts
          submodules: true

      - name: Install dependecies
        run: brew install libtool autoconf automake pkg-config bison re2c

      - name: "Building php to MacoS arm64"
        continue-on-error: true
        run: |
          export PATH="/usr/local/opt/bison/bin:${PATH}"
          ./compile.sh -t mac-arm64 -f -g -j$(nproc)

      - name: Show Log
        run: cat *.log

      - name: Create tarball
        run: zip macos_arm64.zip bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos_arm64
          path: |
            *.zip
            *.log
  linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: pmmp/php-build-scripts
          submodules: true

      - name: Linux Depencies Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y build-essential make wget gzip bzip2 bison git cmake re2c autoconf automake pkg-config libtool* unzip zip

      - name: "Building php bin"
        continue-on-error: true
        run: ./compile.sh -j$(nproc)

      - name: Show Log
        run: cat *.log

      - name: Create tarball
        run: zip linux_x64.zip bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux_x64
          path: |
            *.zip
            *.log
  android:
    runs-on: ubuntu-latest
    name: Android
    container:
      image: ghcr.io/the-bds-maneger/android_musl:latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: pmmp/php-build-scripts
          submodules: true

      - name: Linux Depencies Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y build-essential make wget gzip bzip2 bison git cmake re2c autoconf automake pkg-config libtool* unzip zip

      - name: "Building php bin"
        continue-on-error: true
        run: ./compile.sh -t android-aarch64 -x -f -g -j$(nproc)

      - name: Show Log
        run: cat *.log

      - name: Create tarball
        run: zip linux_aach64.zip bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android_aarch64
          path: |
            *.zip
            *.log
  win32:
    runs-on: windows-2019
    name: Windows
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: pmmp/php-build-scripts
          submodules: true

      - name: Windows Depencies Install
        if: runner.os == 'Windows'
        run: choco install wget --no-progress

      - name: "Building php bin"
        continue-on-error: true
        run: .\windows-compile-vs.bat
      
      - name: show log
        run: type compile.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: |
            php-*.zip